-- OpenClaw marketplace v1 schema (PostgreSQL)

create table if not exists users (
  id bigint generated by default as identity primary key,
  email varchar(255) unique not null,
  password_hash varchar(255) not null,
  display_name varchar(100) not null,
  avatar_url varchar(500),
  status varchar(20) not null,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists user_roles (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id),
  role varchar(30) not null,
  created_at timestamptz not null,
  unique(user_id, role)
);

create table if not exists agent_owner_profiles (
  id bigint generated by default as identity primary key,
  user_id bigint unique not null references users(id),
  headline varchar(255) not null,
  bio text,
  pricing_note varchar(255),
  service_status varchar(20) not null,
  rating_avg numeric(3,2) default 0,
  rating_count int default 0,
  completed_order_count int default 0,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists task_templates (
  id bigint generated by default as identity primary key,
  code varchar(64) unique not null,
  name varchar(100) not null,
  task_type varchar(64) not null,
  description text not null,
  input_schema jsonb not null,
  output_schema jsonb not null,
  acceptance_schema jsonb not null,
  pricing_model varchar(30) not null,
  base_price numeric(12,2),
  sla_hours int not null,
  status varchar(20) not null,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists capability_packages (
  id bigint generated by default as identity primary key,
  owner_user_id bigint not null references users(id),
  title varchar(255) not null,
  summary text not null,
  task_template_id bigint not null references task_templates(id),
  sample_deliverables jsonb,
  price_min numeric(12,2),
  price_max numeric(12,2),
  capacity_per_week int not null,
  status varchar(20) not null,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  order_no varchar(50) unique not null,
  buyer_user_id bigint not null references users(id),
  owner_user_id bigint references users(id),
  task_template_id bigint not null references task_templates(id),
  capability_package_id bigint references capability_packages(id),
  title varchar(255) not null,
  status varchar(30) not null,
  quoted_price numeric(12,2) not null,
  currency varchar(10) not null default 'USD',
  sla_hours int not null,
  requirement_payload jsonb not null,
  accepted_at timestamptz,
  delivered_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists deliverables (
  id bigint generated by default as identity primary key,
  order_id bigint not null references orders(id),
  version_no int not null,
  delivery_note text,
  deliverable_payload jsonb not null,
  submitted_by bigint not null references users(id),
  submitted_at timestamptz not null,
  unique(order_id, version_no)
);

create table if not exists acceptance_reviews (
  id bigint generated by default as identity primary key,
  order_id bigint not null references orders(id),
  deliverable_id bigint not null references deliverables(id),
  reviewer_user_id bigint not null references users(id),
  decision varchar(30) not null,
  checklist_result jsonb not null,
  comment text,
  reviewed_at timestamptz not null
);

create table if not exists settlements (
  id bigint generated by default as identity primary key,
  order_id bigint unique not null references orders(id),
  payment_status varchar(30) not null,
  payment_channel varchar(30),
  escrow_amount numeric(12,2) not null,
  platform_fee numeric(12,2) not null,
  owner_payout_amount numeric(12,2) not null,
  escrowed_at timestamptz,
  released_at timestamptz,
  refunded_at timestamptz,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists disputes (
  id bigint generated by default as identity primary key,
  order_id bigint not null references orders(id),
  opened_by bigint not null references users(id),
  reason_code varchar(50) not null,
  description text not null,
  status varchar(30) not null,
  resolution_note text,
  resolved_at timestamptz,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists order_events (
  id bigint generated by default as identity primary key,
  order_id bigint not null references orders(id),
  actor_user_id bigint references users(id),
  event_type varchar(50) not null,
  event_payload jsonb,
  created_at timestamptz not null
);

create index if not exists idx_orders_buyer_status on orders(buyer_user_id, status);
create index if not exists idx_orders_owner_status on orders(owner_user_id, status);
create index if not exists idx_orders_template_status on orders(task_template_id, status);
create index if not exists idx_capability_packages_owner_status on capability_packages(owner_user_id, status);
create index if not exists idx_task_templates_task_type_status on task_templates(task_type, status);
create index if not exists idx_disputes_order_status on disputes(order_id, status);
create index if not exists idx_order_events_order_created on order_events(order_id, created_at desc);
