import { randomUUID } from "node:crypto";
import { deliverables, orders, templates } from "../data";
import { Order, OrderState } from "../types";

const stateTransitions: Record<OrderState, OrderState[]> = {
  created: ["accepted", "cancelled"],
  accepted: ["in_progress", "cancelled"],
  in_progress: ["delivered", "disputed"],
  delivered: ["rejected", "accepted_final", "disputed"],
  rejected: ["in_progress", "disputed"],
  accepted_final: ["settled"],
  settled: [],
  cancelled: [],
  disputed: ["settled"]
};

export class OrderService {
  static list(): Order[] {
    return orders;
  }

  static get(orderId: string): Order | undefined {
    return orders.find((order) => order.id === orderId);
  }

  static create(params: {
    templateId: string;
    packageId: string;
    buyerId: string;
    inputs: Record<string, unknown>;
    currency?: string;
    escrowAmount?: number;
  }): Order {
    const template = templates.find((tpl) => tpl.id === params.templateId);
    if (!template) {
      throw new Error("Template not found");
    }

    const timestamp = new Date().toISOString();
    const order: Order = {
      id: randomUUID(),
      templateId: params.templateId,
      packageId: params.packageId,
      buyerId: params.buyerId,
      inputs: params.inputs,
      state: "created",
      currency: params.currency ?? "USD",
      escrowAmount: params.escrowAmount ?? template.pricing.basePrice,
      createdAt: timestamp,
      updatedAt: timestamp
    };
    orders.push(order);
    return order;
  }

  static transition(orderId: string, nextState: OrderState): Order {
    const order = this.get(orderId);
    if (!order) {
      throw new Error("Order not found");
    }
    const allowed = stateTransitions[order.state];
    if (!allowed.includes(nextState)) {
      throw new Error(`Invalid transition ${order.state} -> ${nextState}`);
    }
    order.state = nextState;
    order.updatedAt = new Date().toISOString();
    if (nextState === "delivered") {
      deliverables.push({
        id: randomUUID(),
        orderId,
        version: 1,
        summary: "Autogenerated delivery placeholder",
        artifactUrl: "https://files.example.com/placeholder",
        submittedAt: order.updatedAt
      });
    }
    return order;
  }
}
